# Generated by Django 5.2.2 on 2025-06-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
